from resumelens.normalization.framework_fst import framework_fst
from resumelens.normalization.tech_fst import language_fst, database_fst, tool_fst

def number(state):
    return int(str(state)[1:])

def show_symbol(symbol):
    if symbol == " ":
        return "␣"
    return str(symbol)

def tuple_text(fst):
    states = sorted(fst.states, key=number)
    sigma = sorted(show_symbol(s) for s in fst.input_symbols)
    gamma = sorted(str(s) for s in fst.output_symbols)
    final = [str(s) for s in sorted(fst.final_states, key=number)]
    return ("- Q = {q0, q1, ..., " + str(states[-1]) + "}  (" + str(len(states)) + " states)\n"
            "- Σ = {" + ", ".join(sigma) + "}\n"
            "- Γ = {" + ", ".join(gamma) + "}\n"
            "- q0 = q0\n"
            "- F = {" + ", ".join(final) + "}\n"
            "- Number of transitions: " + str(fst.get_number_transitions()))

def to_mermaid(fst):
    edges = []
    for (source, letter), destinations in fst.transitions.items():
        for target, output in destinations:
            edges.append((source, letter, target, output))
    edges.sort(key=lambda e: number(e[2]))
    lines = ["```mermaid", "stateDiagram-v2", "    direction LR", "    [*] --> q0"]
    for source, letter, target, output in edges:
        text = output[0] if output else "ε"
        lines.append("    " + str(source) + " --> " + str(target) + " : "
                     + show_symbol(letter) + " / " + text)
    for state in sorted(fst.final_states, key=number):
        lines.append("    " + str(state) + " --> [*]")
    lines.append("```")
    return "\n".join(lines)

parts = ["# Transducer diagrams (generated by make_fst_docs.py)\n"]
for name, fst in [("Frameworks", framework_fst), ("Languages", language_fst),
                  ("Databases", database_fst), ("Tools", tool_fst)]:
    parts.append("## " + name + " transducer\n")
    parts.append(tuple_text(fst) + "\n")
    parts.append(to_mermaid(fst) + "\n")

with open("docs/transducer_diagrams.md", "w", encoding="utf-8") as f:
    f.write("\n".join(parts))
print("docs/transducer_diagrams.md created")